### ISSUE TITLE
chessboard target

### ISSUE THREAD

**Issue by Sinchiguano** [IFL-CAMP/easy_handeye#45]
Hi,

Is it possible to execute the eye in hand calibration with a chessboard target? 

Best regards
Cesar

**Comment by marcoesposito1988** [comment]
Hi @Sinchiguano,

you can use any tracking system that publishes the pose of the marker in tf. 

Your question has actually a perfect timing, since I just started working on Yet Another Aruco Wrapper because I couldn't find any that satisfied all of my needs (including detecting a charuco board). As soon as this is ready, I will publish it together with documentation on how to use it with `easy_handeye`.

**Comment by marcoesposito1988** [comment]
I published a the new wrapper for ArUco, compatible also with ChArUco boards, as [easy_aruco](https://github.com/marcoesposito1988/easy_aruco). I will soon publish launch files to use it directly with `easy_handeye`, but you can already take a look at it if you wish.

**Comment by kingjin94** [comment]
I think you can also use this package: http://wiki.ros.org/tuw_checkerboard

**Comment by marcoesposito1988** [comment]
I evaluated it, but it only supports checkerboards and not markers. So I just wrote a wrapper that supports both.

Thanks anyway!
