### ISSUE TITLE
Robot base position if robot is not on the ground

### ISSUE THREAD

**Issue by ranjitkathiriya** [IFL-CAMP/easy_handeye#80]
Hello,

I am using the easy_handeye package for my robot. I am using eye-in-hand as a calibration. 

I have a question:

1. As describe in a screenshot my robot_base and world position id different. I should use which position as a robot_base_frame? It should be robot_base or world?

```
<launch>
  <!-- (start your robot's MoveIt! stack, e.g. include its moveit_planning_execution.launch) -->
  <!-- (start your tracking system's ROS driver) -->

  <include file="$(find easy_handeye)/launch/calibrate.launch">
    <arg name="eye_on_hand" value="true"/>

    <!-- you can choose any identifier, as long as you use the same for publishing the calibration -->
    <arg name="namespace_prefix" value="my_eih_calib"/>

    <!-- fill in the following parameters according to your robot's published tf frames -->
    <arg name="robot_base_frame" value="/base_link"/>
    <arg name="robot_effector_frame" value="/ee_link"/>

    <!-- fill in the following parameters according to your tracking system's published tf frames -->
    <arg name="tracking_base_frame" value="/optical_origin"/>
    <arg name="tracking_marker_frame" value="/optical_target"/>
  </include>
</launch>

```

![Screenshot from 2021-05-04 12-03-28](https://user-images.githubusercontent.com/12687608/117442205-5c7d3d00-af2e-11eb-85d9-9f5080fa88c9.png)

**Comment by marcoesposito1988** [comment]
Hi @ranjitkathiriya,

if this is an eye-in-hand calibration, the base frame is indifferent. The result of the calibration will be between the chosen end effector frame and the camera frame. 

Just for reference, if it were an eye-on-base calibration, it still wouldn't matter as long as you are using `easy_handeye`'s publisher. Otherwise you would have to pay attention to the frames you chose when transferring the resulting transformation to the other program.

**Comment by ranjitkathiriya** [comment]
> if this is an eye-in-hand calibration, the base frame is indifferent. The result of the calibration will be between the chosen end effector frame and the camera frame.

Yes, I am using an eye-in hand. Thanks! I got it.
